CUSTOM_FIELD = {
    "HR Policy":[
        {
            "dt":"HR Policy",
            "default": "0",
            "fieldname": "enable_leave_surrender",
            "fieldtype": "Check",
            "label": "Enable Leave Surrender",
            "insert_after": "employee_salary_component_percentage",
        },
        {
            "dt":"HR Policy",
            "depends_on": "eval:doc.enable_leave_surrender;",
            "fieldname": "leave_salary_component",
            "fieldtype": "Link",
            "label": "Leave Salary Component",
            "mandatory_depends_on": "eval:doc.enable_leave_surrender;",
            "options": "Salary Component",
            "insert_after": "enable_leave_surrender",
        },
        {
            "dt":"HR Policy",
            "depends_on": "eval:doc.enable_leave_surrender;",
            "fieldname": "surrender_leave_type",
            "fieldtype": "Link",
            "label": "Surrender Leave Type",
            "mandatory_depends_on": "eval:doc.enable_leave_surrender;",
            "options": "Leave Type",
            "insert_after": "enable_leave_surrender",
        },
        {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "0",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "HR Policy",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_enable_incentive",
            "fieldtype": "Check",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "employee_salary_component_percentage",
            "is_system_generated": 1,
            "is_virtual": 0,
            "label": "Enable Incentive",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "HR Policy-custom_enable_incentive",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "eval:doc.custom_enable_incentive;",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "HR Policy",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_incentive_component",
            "fieldtype": "Link",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_enable_incentive",
            "is_system_generated": 1,
            "is_virtual": 0,
            "label": "Incentive Component",
            "length": 0,
            "mandatory_depends_on": "eval:doc.custom_enable_incentive;",
            "module": "",
            "name": "HR Policy-custom_incentive_component",
            "no_copy": 0,
            "non_negative": 0,
            "options": "Salary Component",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
        
    ],
    "Payroll Entry":[
        {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Payroll Entry",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_sharing__incentive",
            "fieldtype": "Tab Break",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "salary_slips_submitted",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Sharing  Incentive",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Payroll Entry-custom_sharing__incentive",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "eval:!doc.custom_enable_sharing_incentive",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Payroll Entry",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_enable_sharing_incentive",
            "fieldtype": "Check",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_sharing__incentive",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Enable Sharing Incentive",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Payroll Entry-custom_enable_sharing_incentive",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 1,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Payroll Entry",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_incentive_salary_component",
            "fieldtype": "Link",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_enable_sharing_incentive",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Incentive Salary Component",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Payroll Entry-custom_incentive_salary_component",
            "no_copy": 0,
            "non_negative": 0,
            "options": "Salary Component",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 1,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Payroll Entry",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_amount",
            "fieldtype": "Currency",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_incentive_salary_component",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Amount",
            "length": 0,
            "mandatory_depends_on": "eval:doc.custom_enable_sharing_incentive;",
            "module": "",
            "name": "Payroll Entry-custom_amount",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "eval:!doc.custom_enable_sharing_incentive",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
    ]
}